### ISSUE TITLE
Force PNG32 for macstore iconset

### ISSUE THREAD

**Issue by ghost** [moderna/ma-image-resize-tool#10]
The macstore.iconset used within the app has to be PNG32. The corresponding IM command is:
```convert "input.png" "PNG32:output.png"```

**Comment by geo-at-github** [comment]
You can do this by using the image magick "-define" parameter. See: http://www.imagemagick.org/script/command-line-options.php
Don't forget to also deactivate the optimization (otherwise it would be reduced again to 8-bit png).

Example:
`{ ... "imageMagicParameters":"-unsharp 1.5x1+0.7+0.02 -define png:format=png32", "optimize": false },`

This will be added as default setting to the "apple-macstore-icons" templates soon.
Thanks

**Comment by geo-at-github** [comment]
Has been added now.
